package es.NTTEnterprise.RIntellix.ms_reporting.domain.enums;

/**
 * Type of report generated by the microservice.
 * 
 * @author Lucía Fernández Mancebo
 * @date 29/06/2026
 */
public enum ReportType {
    
    /**
     * Detailed Credit Risk Analysis Report.
     */
    RISK_ANALYSIS
}
